name: Container Startup

on: push

jobs:
  container-startup:
    runs-on: ubuntu-22.04
    timeout-minutes: 5

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Install make
      run: sudo apt-get update && sudo apt-get install -y make
    - name: Docker containers will start up within 180 seconds
      run: |
        timeout 180s make up || {
          echo ">>>>>>>>>> FAILURE <<<<<<<<<<"
          exit 1
        }
    - name: Verify all containers are running
      run: |
        if docker ps | grep -q "Restarting"; then
          echo ">>>>>>>>>> FAILURE <<<<<<<<<<"
          docker logs
          exit 1
        fi
        echo ">>>>>>>>>> SUCCESS <<<<<<<<<<"
