name: Container Startup

on: push

jobs:
  container-startup:
    runs-on: ubuntu-22.04
    timeout-minutes: 5

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Install make
      run: sudo apt-get update && sudo apt-get install -y make

    - name: Start containers with timeout
      run: |
        echo "Starting containers with 120 second timeout..."
        timeout 120s make up || {
          echo "❌ Containers failed to start within 120 seconds"
          exit 1
        }
        echo "✅ Containers started successfully within 120 seconds"

    - name: Verify all containers are running
      run: |
        echo "Checking container status..."
        docker-compose ps

        # Check if all containers are in 'running' state
        if docker-compose ps | grep -q "|Restarting"; then
          echo "❌ Some containers are not running properly"
          docker-compose logs
          exit 1
        fi

        echo "✅ All containers are running successfully"

    - name: Cleanup
      if: always()
      run: |
        echo "Cleaning up containers..."
        make down || true
        docker system prune -f
